language: c

script:

  - git clone https://github.com/xtuple/xtuple.git  
  - cd ../xtuple
  - git checkout 4_6_x
  - cd ..

  - cd bi-open/scripts
  - bash build_bi.sh -eblm -c ../../xtuple/node-datasource/config.js -d demo_dev -P qwerty

after_failure:
  - sudo cat /var/spool/cron/crontabs/travis
  - sudo cat /var/spool/cron/crontabs/root
  - sudo find / -name xtuple-server.log
  - sudo cat xtuple-server.log
  - env