language: c

env:
  global:
    - M2_HOME=/usr/share/maven

script:
  # Bootstrap
  - wget git.io/hikK5g -qO- | sudo bash
  
  # Install server. Can't use npm because of user propmt?
  - npm install -g xtuple-server

  # The FOSS xtuple-server requires an existing xtuple directory to start working off of
  - cd ..
  - git clone https://github.com/xtuple/xtuple.git
  - git clone https://github.com/xtuple/xtuple-extensions.git

  - sudo n 0.8  # TODO no sudo here!
  - cd xtuple-extensions
  - git checkout 4_7_x
  - git submodule update --init --recursive --quiet
  - npm install --quiet
  
  - cd ../xtuple
  - git checkout v4.6.0-1
  - git submodule update --init --recursive --quiet
  - npm install --quiet
  - cd ..

  # Use the server to do an install
  # must be n 0.11
  - sudo xtuple-server install-dev --xt-version 4.5.1 --xt-demo --local-workspace ./xtuple --xt-adminpw admin

  # Install BI and perform ETL
  - cd bi-open/scripts
  - sudo bash build_bi.sh -ebm -c ../../xtuple/node-datasource/config.js -d demo_dev -P admin
  - cd ../../bi-open/scripts
  - sudo bash build_bi.sh -l -c ../../xtuple/node-datasource/config.js -d demo_dev -P admin
  - sudo bash start_bi.sh

  # Install bi-open.
  - cd ../../xtuple
  - sudo n 0.8
  - ./scripts/build_app.js -d demo_dev -e ../xtuple-extensions/source/bi_open

  # Start the app.
  - node node-datasource/main.js &
  - sleep 10

  # Run a test to make sure that BI is accessible and the ETL worked
  - cd ../xtuple-extensions
  #- cat test/lib/sample_login_data.js | sed 's#org:.*#org: \"demo_dev\",#' > test/lib/login_data.js
  - cp ../xtuple/test/lib/login_data.js test/lib/login_data.js
  - npm run-script test-bi_open

after_failure:
  - sudo cat /var/spool/cron/crontabs/travis
  - sudo cat /var/spool/cron/crontabs/root
  - sudo find / -name xtuple-server.log
  - sudo cat xtuple-server.log
  - env
