language: c
source_key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeTFtbEtpYTlwYmZDNUVmQ3RmMHlVREJyalphY3IrRzJXV1NqMll3ckNoeHg2ZFJsCnZLbmttMFdoWklwb3ljMXNnZGdJVXdJTnVkVWFSR1hVcUQ3aUsvUjZmSlJqWVBZZ2pLeVZrejR3WVU5Um14VHcKeXljMHJ6LzM0bSt0QU9NSVJMWnJDdDY4bUdlbEJiNTVONER4dUpDV2Jyakx0d3FBTTdESSszZm5QcGFTdExYdwpNQ09FRFZwWDF6N2Vocjd2Vmx3WnBnVjVkbFRiS0FQUDdabktvUVhoSmRFczRCNWZwQTFLWU9PcWF0UnU1enJ0CkxTMmRucGJJZm4raFVkMzh1Vk55NUc1NzFHNk94cTUvcnA4RWxyTHFtenEyRk05NVBVcUhQZTFOdVFhWFVEdDAKSDAzQUhjUHBYcXpCeTJoYVl1TUhHVytDYTNpQ29kcXpOYnl0QndJREFRQUJBb0lCQVFDbXo2NEdpdXN0d3pYVAp6KzR4SGpna3dlT29yWEZ4Y21ZRXBPTW9OYXlreWJyRWgyREJ5RmhvNjFDK3lpKzF3NWNNV0t4VGM2N1F6N2lSCmZUdGFuT01xRFk1aEhkVDhHRXVST280azBISWRrVlN2TkJsbmZZemhha2N0Y0ZEcUZsT1ZFbE56QWs2UmN3eFQKVHZIZkR4NjdPWmk5MFVnRHFsQ0tscTM0WTE3RjNvWWdZaFk0NTlId2FxNm0vYWFPTjdRbzlCZ1BkelEvMmUzQgpIUGhEczI4a1BwWkl5UkMyS2g4Kzh2NlVvU09ZMjg1dmMzRlRGRGs5bXM3dXZvU09MbmJUV2FwYXBLL1BPM2xlCjlhNEMwNHVBSTZnQWMzeFBGYnNHemx1SXhYWmdFaWdYdlZyRm1yazI1Q2VqeFI5NDJGdndGZmhYRHp2MEFkRmoKZmR1anZQaUJBb0dCQVBGN2U5a0R6NzkzTGxyY1RkanNXUW0xajlzeC8rUS9EUG5KYlNkSmR2bVlVZ1p1YkErLwpoR1ZDVlpMeHdPdU1TUVhZVlZkblRuSTQxNitqbUxEb3YrYVlBVEdjV3VFS0NFRDZBVmk3MUZRd3FaV3dXYmVnCnRUMVRUK1VXV1c4eDZjYktzeUVNc3RZTTd6WHZTdXhycVhOYzhEOU5FNmg4WHpjdnRNb1ZQNjNIQW9HQkFOZVQKU25maGc1Mko0TzFuNk5IR3NQTndZMU9vNEcvekg4Sllsd1lMdGpJTVNoeG5ZOWw2Mmx4UlVSb0ZFVTZHRjRlNgpVcUczeFBmdXUvSnNzbjdzZG0xNDV5NmxwOVZFSCtTUHNrSEhZV0ZEY2lTMEh0VUJBNUp3T2lLb0J4STRNbndhCnlPV2xka0k3akIrZzhJUHhQVEpFY0NnMHM2VVUyTWpWSXJOWUdBYkJBb0dBWWtGbVVSVFY4UWZqV3FFTkk5aDMKR2haQUpHWWh3cE5OQ2szRkZoazBTYmFLbVlkUWZNL21aUFVxc0pHaGQ3WXErQy9mK2FKVkx2Q21BaGRFeDZiTQpmbDBYRDBLWlQ3dXZSQkQxZjA5ZHc2dlJOTkQra0ZMWnE4dzhVL0JXRDRKMXBxZFBYNEUxT3hja05nUFpybnpZCkE5S3JCbmFzS3dBQUZncFpPMmlOOG4wQ2dZQnNvMUtjOVc0QmYxRjE4cTZXd1AyOXdMNmRrM1ovbEZORitxVXAKSzgvR2l3RHlMWHhaUmhzeStOdlpOQUtUd3VtcXdkQVFwVzdDejNHeDZ1dE5JVmRSTmVPelUxSXdIS1BCNkZTWgo1Nk9BZzUvTE5XWndTNUdFUThCWVpMc2ppR1NRdkdMUHNFSFhnUERObzZweG82b0dZZ3p2aGhlZU10Skk2M2dRClQyM1VRUUtCZ1FEVjR4QklPeHMzNDB2WTBVOU9mNGtaSG55Nm5xWS9KK0RaOTZBQ0U5MUdoL0p4UkwwcXBIZXkKNjVSVXl5OTVQYWR4TVAwVXZWcHBMSldORVEvTlhETXlhQWdXYXhpa1NzS3NGSTh6Sy95WS9zSGdEeDQveUNmUwpUaEViVzZVTExxZEd3bUpTT3ltc3ZyK0FRU0pKeG9xZmZweDlIOEt6MVRQTDZadytnTjd4Q3c9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="

script:
  # Bootstrap
  - wget git.io/hikK5g -qO- | sudo bash
  
  # Install server. Can't use npm because of user propmt?
  - npm install -g xtuple-server

  # The FOSS xtuple-server requires an existing xtuple directory to start working off of
  - cd ..
  - git clone https://github.com/xtuple/xtuple.git
  - git clone https://github.com/jgunderson/xtuple-extensions.git

  # Temporary hack: we need the bleeding-edge code to access the BI reshuffle. XXX remove after 4.6 beta
  - n 0.8
  - cd xtuple-extensions
  - git checkout ci-chg2
  - git submodule update --init --recursive --quiet
  - npm install --quiet
  
  # Do we need to be back to node 11 for xtuple npm?  of can we use:
  # npm update -g npm
  - cd ../xtuple
  - git checkout 4_6_x
  - git submodule update --init --recursive --quiet
  - npm install --quiet
  - cd ..

  # Use the server to do an install
  # must be n 0.11
  - sudo xtuple-server install-dev --xt-version 4.5.1 --xt-demo --local-workspace ./xtuple --xt-adminpw admin

  # Install BI and perform ETL
  - git clone https://github.com/jgunderson/bi-open.git
  - cd bi-open/scripts
  - git checkout ci-chg2
  - bash build_bi.sh -ebm -c ../../xtuple/node-datasource/config.js -d demo_dev -P admin
  - cd ../../bi/scripts
  - bash install.sh
  - cd ../../bi-open/scripts
  - bash build_bi.sh -l -c ../../xtuple/node-datasource/config.js -d demo_dev -P admin
  - bash start_bi.sh

  # Install bi-open.
  - cd ../../xtuple
  - n 0.8
  - ./scripts/build_app.js -d demo_dev -e ../xtuple-extensions/source/bi_open

  # Start the app.
  - npm start &
  - sleep 10

  # Run a test to make sure that BI is accessible and the ETL worked
  - cd ../private-extensions
  #- cat test/lib/sample_login_data.js | sed 's#org:.*#org: \"demo_dev\",#' > test/lib/login_data.js
  - cp ../xtuple/test/lib/login_data.js test/lib/login_data.js
  - npm run-script test-bi

after_failure:
  - sudo cat /var/spool/cron/crontabs/travis
  - sudo cat /var/spool/cron/crontabs/root
  - sudo find / -name xtuple-server.log
  - sudo cat xtuple-server.log
  - env
