language: c

script:
  # Basic setup of the xtuple-server, from the xtuple-server wiki
  - wget git.io/hikK5g -qO- | sudo bash
  - npm install -g xtuple-server
  - cd ..

  # The FOSS xtuple-server requires an existing xtuple directory to start working off of
  - git clone https://github.com/xtuple/xtuple.git
  - git clone https://github.com/xtuple/xtuple-extensions.git

  # Temporary hack: we need the bleeding-edge code to access the BI reshuffle. XXX remove after 4.6 beta
  - cd xtuple-extensions
  - git checkout 4_6_x
  - git submodule update --init --recursive
  - npm install
  
  - cd ../xtuple
  - git checkout 4_6_x
  - cd ..

  # Use the server to do an install
  - sudo xtuple-server install-dev --xt-version 4.5.1 --xt-demo --local-workspace ./xtuple --xt-adminpw admin

  # Install BI and perform ETL
  - cd bi-open/scripts
  - bash build_bi.sh -eblm -c ../../xtuple/node-datasource/config.js -d demo_dev -P admin
  - mvn -v
  
  - bash start_bi.sh

  # Install the bi-open extension. TODO: build this into the xtuple-server install as a flag
  - n 0.8
  - cd ../../xtuple
  - ./scripts/build_app.js -d demo_dev -e ../xtuple-extensions/bi-open

  # Start the app.
  - npm start &
  - sleep 10

  # Run a test to make sure that BI is accessible and the ETL worked
  - cd ../xtuple-extensions
  - cat test/lib/sample_login_data.js | sed 's#org:.*#org: \"demo_dev\",#' > test/lib/login_data.js
  - npm run-script test-bi_open

after_failure:
  - sudo cat /var/spool/cron/crontabs/travis
  - sudo cat /var/spool/cron/crontabs/root
  - sudo find / -name xtuple-server.log
  - sudo cat xtuple-server.log
  - env